# Simple Analysis with Pandas and Numpy

***ABSTRACT***
* If a donor gives aid for a project that the recipient government would have undertaken anyway, then the aid is financing some expenditure other than the intended project. The notion that aid in this sense may be "fungible," while long recognized, has recently been receiving some empirical support. The paper "What Does Aid to Africa Finance?" focuses on Sub-Saharan Africa—the region with the largest GDP share of aid—and presents results that indicate that aid may be partially fungible, and suggests some reasons why.

This database contains data used for the analysis.

#### Import Libraries & Load the data

In [1]:
import pandas as pd
import numpy as np

print('OK')

OK

In [2]:
df = pd.read_csv('data.csv')
df.head(-5)

,countryc,year,agrgdp,popn,infmort,schprim,schsec,grtdsbp,grlndsbp,aiddsbp,...,dcurexpp,dcapexpp,dprirepp,dcnlnagp,dcnlnenp,dcnlninp,dcnlntacp,dcnlnedup,dcnlnhthp,dcnlnothp
0,Burkina Faso,1970,35.44188862,5633000.0,141.3999939,13,1,13.3182802200317,1.02303504943848,14.3413200378418,...,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308
1,Burkina Faso,1970,35.44188862,5633000.0,141.3999939,13,1,13.3182802200317,1.02303504943848,14.3413200378418,...,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308
2,Burkina Faso,1971,36.16739069,5740700.0,139.1999969,13.6,1.2,16.7043991088867,0.655763506889343,17.3601703643799,...,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308
3,Burkina Faso,1972,37.51058767,5848380.0,137,14.2,1.4,20.9176502227783,2.97720909118652,23.8948593139648,...,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308
4,Burkina Faso,1973,34.83428571,5958700.0,135,14.8,1.6,25.9791507720947,3.87817406654358,29.8573207855225,...,1.79769313486232e+308,1.79769313486232e+308,-4.26292991638184,0.290098994970322,0.0578910000622272,2.53049802780151,-0.38238000869751,0,0,-0.11642000079155
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291,Malawi,1971,44.33026223,4651300.0,192.1999969,45,3,16.4472007751465,14.293740272522,30.7409400939941,...,1.79769313486232e+308,1.79769313486232e+308,6.88956022262573,-0.0955099985003471,1.32390594482422,0,1.74581897258759,-1.70571994781494,0,-7.2340898513794
292,Malawi,1972,45.63138806,4790790.0,191,47.2,3,9.18033123016357,16.4357490539551,25.6160907745361,...,2.44229292869568,-1.76150000095367,-6.65278005599976,1.00990498065948,0.331779003143311,0,-2.001620054245,-0.48895001411438,0,2.88150310516357
293,Malawi,1973,41.5786385,4936110.0,188.2,49.4,3,7.64392709732056,12.3378896713257,19.981819152832,...,-4.00758981704712,4.35508298873901,0.357174009084702,-0.814429998397827,-1.71546995639801,0,-1.69972002506256,-0.134709998965263,0,1.07293200492859
294,Malawi,1974,41.17239788,5087140.0,185.4,51.6,4,8.73302841186524,15.7701101303101,24.5031394958496,...,0.46765199303627,7.48967599868774,-0.0427899993956089,1.00035405158997,0.44098699092865,0,1.25282204151154,0.21764700114727,0,-4.72225999832153
295,Malawi,1975,37.23468769,5244000.0,182.6,53.8,4,10.5895004272461,22.165210723877,32.754711151123,...,0.515770971775055,10.8334703445435,0.043698001652956,-0.280800014734268,0.483336985111237,0.184547007083893,7.19747400283814,-0.14614999294281,0,0.320367008447647

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 50 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   countryc   301 non-null    object
 1   year       301 non-null    int64
 2   agrgdp     301 non-null    object
 3   popn       297 non-null    float64
 4   infmort    301 non-null    object
 5   schprim    301 non-null    object
 6   schsec     301 non-null    object
 7   grtdsbp    301 non-null    object
 8   grlndsbp   301 non-null    object
 9   aiddsbp    301 non-null    object
 10  totexpp    301 non-null    object
 11  agexpp     301 non-null    object
 12  enexpp     301 non-null    object
 13  indexpp    301 non-null    object
 14  tacexpp    301 non-null    object
 15  eduexpp    301 non-null    object
 16  hthexpp    301 non-null    object
 17  prirepp    301 non-null    object
 18  curexpp    301 non-null    object
 19  capexpp    301 non-null    object
 20  gdnpp      301 non-null    object
 21  d0         301 non-null    object
 22  cnlnagp    301 non-null    object
 23  cnlnenp    301 non-null    object
 24  cnlninp    301 non-null    object
 25  cnlntacp   301 non-null    object
 26  cnlnedup   301 non-null    object
 27  cnlnhthp   301 non-null    object
 28  cnlnothp   301 non-null    object
 29  dgrtdsbp   301 non-null    object
 30  dgrlndsbp  301 non-null    object
 31  daiddsbp   301 non-null    object
 32  dtotexpp   301 non-null    object
 33  dagexpp    301 non-null    object
 34  denexpp    301 non-null    object
 35  dindexpp   301 non-null    object
 36  dtacexpp   301 non-null    object
 37  deduexpp   301 non-null    object
 38  dhthexpp   301 non-null    object
 39  dothexpp   301 non-null    object
 40  dcurexpp   301 non-null    object
 41  dcapexpp   301 non-null    object
 42  dprirepp   301 non-null    object
 43  dcnlnagp   301 non-null    object
 44  dcnlnenp   301 non-null    object
 45  dcnlninp   301 non-null    object
 46  dcnlntacp  301 non-null    object
 47  dcnlnedup  301 non-null    object
 48  dcnlnhthp  301 non-null    object
 49  dcnlnothp  301 non-null    object
dtypes: float64(1), int64(1), object(48)
memory usage: 117.7+ KB

In [4]:
df_new = df.copy()

df1 = df_new.sample(frac = 0.25, random_state = 0)
df_new = df_new.drop(df1.index)

df1.head(3)

,countryc,year,agrgdp,popn,infmort,schprim,schsec,grtdsbp,grlndsbp,aiddsbp,...,dcurexpp,dcapexpp,dprirepp,dcnlnagp,dcnlnenp,dcnlninp,dcnlntacp,dcnlnedup,dcnlnhthp,dcnlnothp
223,Lesotho,1983,23.91304348,1483270.0,98,106.8,21,87.4762725830078,20.0394096374512,107.515701293945,...,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308
150,"Gambia, The",1988,31.22936246,841250.0,140.7799988,65,15.25,113.245697021484,31.0677890777588,144.313400268555,...,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308
226,Lesotho,1986,21.14252061,1603960.0,92,109,23.4,66.7168197631836,10.6219997406006,77.3388137817383,...,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308

In [5]:
df2 = df_new.sample(frac = 0.25, random_state = 0)
df_new = df_new.drop(df2.index)

df2.head(3)

,countryc,year,agrgdp,popn,infmort,schprim,schsec,grtdsbp,grlndsbp,aiddsbp,...,dcurexpp,dcapexpp,dprirepp,dcnlnagp,dcnlnenp,dcnlninp,dcnlntacp,dcnlnedup,dcnlnhthp,dcnlnothp
168,Kenya,1980,32.59223808,16560000.0,72.40000153,115,20,26.8336296081543,17.7571392059326,44.5907592773438,...,-1.90575003623962,4.4354100227356,-0.64258998632431,-0.43707999587059,-2.52485990524292,-0.424710005521774,-3.0382399559021,-0.0560100004076958,0,7.8144268989563
109,Ghana,1973,48.97463727,9388140.0,106,68.2,27.8,7.54381990432739,7.85923004150391,15.4030504226685,...,-13.4622001647949,-5.45116996765137,-0.186719998717308,-0.00694000022485852,-3.54000997543335,0.0770640000700951,-0.0829199999570846,0,0,-0.743390023708344
204,Liberia,1990,1.79769313486232e+308,2435000.0,176.8,1.79769313486232e+308,1.79769313486232e+308,38.6235008239746,16.2881603240967,54.9116592407227,...,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308

In [6]:
df3 = df_new.sample(frac = 0.25, random_state = 0)

df3.head(3)

,countryc,year,agrgdp,popn,infmort,schprim,schsec,grtdsbp,grlndsbp,aiddsbp,...,dcurexpp,dcapexpp,dprirepp,dcnlnagp,dcnlnenp,dcnlninp,dcnlntacp,dcnlnedup,dcnlnhthp,dcnlnothp
237,Madagascar,1971,24.30771479,6901230.0,176.5999985,91,12,20.3827590942383,4.7145791053772,25.097339630127,...,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308
244,Madagascar,1978,32.22944414,8251580.0,146,100,1.79769313486232e+308,16.9368190765381,8.71989727020264,25.6567192077637,...,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308
299,Malawi,1979,39.64158617,5947940.0,171.4000041,59,4,45.1732597351074,17.5660991668701,62.7393608093262,...,-0.770280003547668,19.4976196289062,2.31688404083252,-0.199290007352829,1.26182305812836,0.375818014144897,-1.21799004077911,-0.732770025730133,0,-0.0970200002193451

In [7]:
df4 = df_new.drop(df3.index) # since all subsets' indexes were dropped
df4.head(3)

,countryc,year,agrgdp,popn,infmort,schprim,schsec,grtdsbp,grlndsbp,aiddsbp,...,dcurexpp,dcapexpp,dprirepp,dcnlnagp,dcnlnenp,dcnlninp,dcnlntacp,dcnlnedup,dcnlnhthp,dcnlnothp
0,Burkina Faso,1970,35.44188862,5633000.0,141.3999939,13,1,13.3182802200317,1.02303504943848,14.3413200378418,...,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308
1,Burkina Faso,1970,35.44188862,5633000.0,141.3999939,13,1,13.3182802200317,1.02303504943848,14.3413200378418,...,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308
2,Burkina Faso,1971,36.16739069,5740700.0,139.1999969,13.6,1.2,16.7043991088867,0.655763506889343,17.3601703643799,...,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308

### Missing Values

* **Interpolation** is a type of estimation, a method of constructing new data points within the range of a discrete set of known data points while **imputation** is replacing the missing data of the mean of the column.

In [8]:
df3.isnull().sum()

countryc     0
year         0
agrgdp       0
popn         1
infmort      0
schprim      0
schsec       0
grtdsbp      0
grlndsbp     0
aiddsbp      0
totexpp      0
agexpp       0
enexpp       0
indexpp      0
tacexpp      0
eduexpp      0
hthexpp      0
prirepp      0
curexpp      0
capexpp      0
gdnpp        0
d0           0
cnlnagp      0
cnlnenp      0
cnlninp      0
cnlntacp     0
cnlnedup     0
cnlnhthp     0
cnlnothp     0
dgrtdsbp     0
dgrlndsbp    0
daiddsbp     0
dtotexpp     0
dagexpp      0
denexpp      0
dindexpp     0
dtacexpp     0
deduexpp     0
dhthexpp     0
dothexpp     0
dcurexpp     0
dcapexpp     0
dprirepp     0
dcnlnagp     0
dcnlnenp     0
dcnlninp     0
dcnlntacp    0
dcnlnedup    0
dcnlnhthp    0
dcnlnothp    0
dtype: int64

In [9]:
df3[df3['popn'].isnull() == True]

,countryc,year,agrgdp,popn,infmort,schprim,schsec,grtdsbp,grlndsbp,aiddsbp,...,dcurexpp,dcapexpp,dprirepp,dcnlnagp,dcnlnenp,dcnlninp,dcnlntacp,dcnlnedup,dcnlnhthp,dcnlnothp
289,Mauritius,1996,9.393333333,NaN,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,...,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308

In [10]:
df3['popn'].fillna(df3['popn'].mean(), inplace = True) # that's called imputation
df3.isnull().sum()

countryc     0
year         0
agrgdp       0
popn         0
infmort      0
schprim      0
schsec       0
grtdsbp      0
grlndsbp     0
aiddsbp      0
totexpp      0
agexpp       0
enexpp       0
indexpp      0
tacexpp      0
eduexpp      0
hthexpp      0
prirepp      0
curexpp      0
capexpp      0
gdnpp        0
d0           0
cnlnagp      0
cnlnenp      0
cnlninp      0
cnlntacp     0
cnlnedup     0
cnlnhthp     0
cnlnothp     0
dgrtdsbp     0
dgrlndsbp    0
daiddsbp     0
dtotexpp     0
dagexpp      0
denexpp      0
dindexpp     0
dtacexpp     0
deduexpp     0
dhthexpp     0
dothexpp     0
dcurexpp     0
dcapexpp     0
dprirepp     0
dcnlnagp     0
dcnlnenp     0
dcnlninp     0
dcnlntacp    0
dcnlnedup    0
dcnlnhthp    0
dcnlnothp    0
dtype: int64

In [11]:
df1.isna().sum()

countryc     0
year         0
agrgdp       0
popn         1
infmort      0
schprim      0
schsec       0
grtdsbp      0
grlndsbp     0
aiddsbp      0
totexpp      0
agexpp       0
enexpp       0
indexpp      0
tacexpp      0
eduexpp      0
hthexpp      0
prirepp      0
curexpp      0
capexpp      0
gdnpp        0
d0           0
cnlnagp      0
cnlnenp      0
cnlninp      0
cnlntacp     0
cnlnedup     0
cnlnhthp     0
cnlnothp     0
dgrtdsbp     0
dgrlndsbp    0
daiddsbp     0
dtotexpp     0
dagexpp      0
denexpp      0
dindexpp     0
dtacexpp     0
deduexpp     0
dhthexpp     0
dothexpp     0
dcurexpp     0
dcapexpp     0
dprirepp     0
dcnlnagp     0
dcnlnenp     0
dcnlninp     0
dcnlntacp    0
dcnlnedup    0
dcnlnhthp    0
dcnlnothp    0
dtype: int64

In [12]:
df1['popn'].fillna(df1['popn'].interpolate(), inplace = True)
df1.isna().sum()

countryc     0
year         0
agrgdp       0
popn         0
infmort      0
schprim      0
schsec       0
grtdsbp      0
grlndsbp     0
aiddsbp      0
totexpp      0
agexpp       0
enexpp       0
indexpp      0
tacexpp      0
eduexpp      0
hthexpp      0
prirepp      0
curexpp      0
capexpp      0
gdnpp        0
d0           0
cnlnagp      0
cnlnenp      0
cnlninp      0
cnlntacp     0
cnlnedup     0
cnlnhthp     0
cnlnothp     0
dgrtdsbp     0
dgrlndsbp    0
daiddsbp     0
dtotexpp     0
dagexpp      0
denexpp      0
dindexpp     0
dtacexpp     0
deduexpp     0
dhthexpp     0
dothexpp     0
dcurexpp     0
dcapexpp     0
dprirepp     0
dcnlnagp     0
dcnlnenp     0
dcnlninp     0
dcnlntacp    0
dcnlnedup    0
dcnlnhthp    0
dcnlnothp    0
dtype: int64

##### When to use interpolation or imputation?
* Data has linear relationship = Interpolation otherwise imputation.

### Combine Data

In [13]:
df5 = df1.join(df2, lsuffix = '_left') # _left indicates columns from left hand side
df5 # NaN = df1 is larger than df2

,countryc_left,year_left,agrgdp_left,popn_left,infmort_left,schprim_left,schsec_left,grtdsbp_left,grlndsbp_left,aiddsbp_left,...,dcurexpp,dcapexpp,dprirepp,dcnlnagp,dcnlnenp,dcnlninp,dcnlntacp,dcnlnedup,dcnlnhthp,dcnlnothp
223,Lesotho,1983,23.91304348,1483270.0,98,106.8,21,87.4762725830078,20.0394096374512,107.515701293945,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150,"Gambia, The",1988,31.22936246,841250.0,140.7799988,65,15.25,113.245697021484,31.0677890777588,144.313400268555,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
226,Lesotho,1986,21.14252061,1603960.0,92,109,23.4,66.7168197631836,10.6219997406006,77.3388137817383,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
296,Malawi,1976,39.20110669,5409980.0,179.8,56,4,14.338809967041,15.4878797531128,29.8267002105713,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,Botswana,1994,5.199306759,1420270.0,55.39999898,117,53,58.7042083740234,16.0785007476807,74.7827072143555,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20,Burkina Faso,1988,48.94457166,8534390.0,107.8,33.5,6.5,35.4728813171387,10.2006902694702,45.6735687255859,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,Botswana,1988,7.060807251,1195140.0,56.6,111.75,35.75,135.776702880859,30.8545207977295,166.631195068359,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158,Kenya,1970,33.29286623,11498000.0,102,58,9,9.42126178741455,9.48890781402588,18.9101696014404,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
230,Lesotho,1990,19.96355858,1783000.0,84.6,105,25,67.9856872558594,26.8740100860596,94.8597030639648,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
179,Kenya,1991,28.14106137,24015140.0,61.4,93,28,29.552059173584,21.131010055542,50.6830711364746,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
# Concat
df6 = pd.concat([df1,df2], axis = 0) # 0 indicates rows
df6

,countryc,year,agrgdp,popn,infmort,schprim,schsec,grtdsbp,grlndsbp,aiddsbp,...,dcurexpp,dcapexpp,dprirepp,dcnlnagp,dcnlnenp,dcnlninp,dcnlntacp,dcnlnedup,dcnlnhthp,dcnlnothp
223,Lesotho,1983,23.91304348,1483270.0,98,106.8,21,87.4762725830078,20.0394096374512,107.515701293945,...,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308
150,"Gambia, The",1988,31.22936246,841250.0,140.7799988,65,15.25,113.245697021484,31.0677890777588,144.313400268555,...,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308
226,Lesotho,1986,21.14252061,1603960.0,92,109,23.4,66.7168197631836,10.6219997406006,77.3388137817383,...,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308
296,Malawi,1976,39.20110669,5409980.0,179.8,56,4,14.338809967041,15.4878797531128,29.8267002105713,...,-3.28504991531372,-12.8143997192383,-0.0718400031328201,-0.538079977035522,0.749620020389557,-0.12015999853611,-2.48820996284485,-0.187729999423027,0,-4.06232023239136
52,Botswana,1994,5.199306759,1420270.0,55.39999898,117,53,58.7042083740234,16.0785007476807,74.7827072143555,...,-187.5,-19.1625995635986,4.24620914459228,-3.0890998840332,4.7163348197937,-2.58439993858337,-1.81132996082306,1.99651896953583,-0.113150000572205,-6.56795978546143
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240,Madagascar,1974,34.22234966,7408570.0,163.2,94,12,16.4736003875732,9.76997661590576,26.243579864502,...,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308
256,Madagascar,1990,32.30721538,11672000.0,101.1600006,87,17,42.6463584899902,13.9560403823853,56.6024017333984,...,1.14905905723572,0.055357001721859,11.8646697998047,2.95013809204102,-0.822669982910156,-0.921169996261597,-2.26319003105164,0.278450012207031,-0.0155899999663234,-2.74889993667603
98,Ethiopia,1988,49.15748278,47643232.0,129.4,34.25,13.5,20.3594608306885,5.55403518676758,25.9134902954102,...,4.41632223129272,-0.611379981040955,0.021629000082612,0.444323003292084,0.412930011749268,0.154944002628326,-1.32232999801636,0.150712996721268,0,-6.21179008483887
23,Burkina Faso,1991,34.66403162,9269910.0,104.2,37,8,38.1004219055176,15.298939704895,53.3993606567383,...,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308
191,Liberia,1977,31.87008374,1708160.0,167,60.66666667,18.33333333,20.3501396179199,29.2217292785644,49.5718688964844,...,-4.21390008926392,-13.3078002929688,-1.24118995666504,1.1413459777832,-2.94400000572205,0,3.02864408493042,1.95925498008728,0,2.47339510917664

#### Inner Join

<img src="https://cdn.sqltutorial.org/wp-content/uploads/2016/03/SQL-INNER-JOIN.png"/>

In [15]:
df7 = pd.merge(df1,df2, on = 'year')
df7

,countryc_x,year,agrgdp_x,popn_x,infmort_x,schprim_x,schsec_x,grtdsbp_x,grlndsbp_x,aiddsbp_x,...,dcurexpp_y,dcapexpp_y,dprirepp_y,dcnlnagp_y,dcnlnenp_y,dcnlninp_y,dcnlntacp_y,dcnlnedup_y,dcnlnhthp_y,dcnlnothp_y
0,Lesotho,1983,23.91304348,1483270.0,98,106.8,21,87.4762725830078,20.0394096374512,107.515701293945,...,-9.00955963134766,-18.8929004669189,1.6323230266571,0.18308499455452,-1.68680000305176,0,-0.067550003528595,0,0,-3.52765011787415
1,Burkina Faso,1983,31.9042673,7490710.0,115.4,24.6,4.2,27.2162609100342,9.1533613204956,36.3696212768555,...,-9.00955963134766,-18.8929004669189,1.6323230266571,0.18308499455452,-1.68680000305176,0,-0.067550003528595,0,0,-3.52765011787415
2,"Gambia, The",1988,31.22936246,841250.0,140.7799988,65,15.25,113.245697021484,31.0677890777588,144.313400268555,...,8.38925743103027,-1.36620998382568,-0.754760026931763,-0.180490002036095,2.19999504089355,-0.662069976329804,-0.273030012845993,-1.6026200056076,0.604721009731293,0.780026018619537
3,"Gambia, The",1988,31.22936246,841250.0,140.7799988,65,15.25,113.245697021484,31.0677890777588,144.313400268555,...,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308
4,"Gambia, The",1988,31.22936246,841250.0,140.7799988,65,15.25,113.245697021484,31.0677890777588,144.313400268555,...,4.41632223129272,-0.611379981040955,0.021629000082612,0.444323003292084,0.412930011749268,0.154944002628326,-1.32232999801636,0.150712996721268,0,-6.21179008483887
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,Madagascar,1973,26.77856578,7230290.0,167.6,93,12,16.3099193572998,8.46950626373291,24.7794303894043,...,-13.4622001647949,-5.45116996765137,-0.186719998717308,-0.00694000022485852,-3.54000997543335,0.0770640000700951,-0.0829199999570846,0,0,-0.743390023708344
138,Madagascar,1973,26.77856578,7230290.0,167.6,93,12,16.3099193572998,8.46950626373291,24.7794303894043,...,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308
139,Madagascar,1973,26.77856578,7230290.0,167.6,93,12,16.3099193572998,8.46950626373291,24.7794303894043,...,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308
140,Madagascar,1973,26.77856578,7230290.0,167.6,93,12,16.3099193572998,8.46950626373291,24.7794303894043,...,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308
141,Madagascar,1973,26.77856578,7230290.0,167.6,93,12,16.3099193572998,8.46950626373291,24.7794303894043,...,1.79769313486232e+308,1.79769313486232e+308,0.349462985992432,0,0,-1.04186999797821,0,0,0,5.01751089096069

#### Full Outer Inclusive Join
<img src="https://cdn.sqltutorial.org/wp-content/uploads/2016/07/SQL-FULL-OUTER-JOIN.png"/>

In [16]:
df8 = pd.merge(df1,df2, how = 'outer')
df8

,countryc,year,agrgdp,popn,infmort,schprim,schsec,grtdsbp,grlndsbp,aiddsbp,...,dcurexpp,dcapexpp,dprirepp,dcnlnagp,dcnlnenp,dcnlninp,dcnlntacp,dcnlnedup,dcnlnhthp,dcnlnothp
0,Lesotho,1983,23.91304348,1483270.0,98,106.8,21,87.4762725830078,20.0394096374512,107.515701293945,...,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308
1,"Gambia, The",1988,31.22936246,841250.0,140.7799988,65,15.25,113.245697021484,31.0677890777588,144.313400268555,...,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308
2,Lesotho,1986,21.14252061,1603960.0,92,109,23.4,66.7168197631836,10.6219997406006,77.3388137817383,...,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308
3,Malawi,1976,39.20110669,5409980.0,179.8,56,4,14.338809967041,15.4878797531128,29.8267002105713,...,-3.28504991531372,-12.8143997192383,-0.0718400031328201,-0.538079977035522,0.749620020389557,-0.12015999853611,-2.48820996284485,-0.187729999423027,0,-4.06232023239136
4,Botswana,1994,5.199306759,1420270.0,55.39999898,117,53,58.7042083740234,16.0785007476807,74.7827072143555,...,-187.5,-19.1625995635986,4.24620914459228,-3.0890998840332,4.7163348197937,-2.58439993858337,-1.81132996082306,1.99651896953583,-0.113150000572205,-6.56795978546143
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126,Madagascar,1974,34.22234966,7408570.0,163.2,94,12,16.4736003875732,9.76997661590576,26.243579864502,...,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308
127,Madagascar,1990,32.30721538,11672000.0,101.1600006,87,17,42.6463584899902,13.9560403823853,56.6024017333984,...,1.14905905723572,0.055357001721859,11.8646697998047,2.95013809204102,-0.822669982910156,-0.921169996261597,-2.26319003105164,0.278450012207031,-0.0155899999663234,-2.74889993667603
128,Ethiopia,1988,49.15748278,47643232.0,129.4,34.25,13.5,20.3594608306885,5.55403518676758,25.9134902954102,...,4.41632223129272,-0.611379981040955,0.021629000082612,0.444323003292084,0.412930011749268,0.154944002628326,-1.32232999801636,0.150712996721268,0,-6.21179008483887
129,Burkina Faso,1991,34.66403162,9269910.0,104.2,37,8,38.1004219055176,15.298939704895,53.3993606567383,...,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308
130,Liberia,1977,31.87008374,1708160.0,167,60.66666667,18.33333333,20.3501396179199,29.2217292785644,49.5718688964844,...,-4.21390008926392,-13.3078002929688,-1.24118995666504,1.1413459777832,-2.94400000572205,0,3.02864408493042,1.95925498008728,0,2.47339510917664

#### Left Inclusive Join
<img src="https://cdn.sqltutorial.org/wp-content/uploads/2016/03/SQL-LEFT-JOIN.png"/>

In [17]:
df9 = pd.merge(df1,df2, how = 'left')
df9

,countryc,year,agrgdp,popn,infmort,schprim,schsec,grtdsbp,grlndsbp,aiddsbp,...,dcurexpp,dcapexpp,dprirepp,dcnlnagp,dcnlnenp,dcnlninp,dcnlntacp,dcnlnedup,dcnlnhthp,dcnlnothp
0,Lesotho,1983,23.91304348,1483270.0,98,106.8,21,87.4762725830078,20.0394096374512,107.515701293945,...,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308
1,"Gambia, The",1988,31.22936246,841250.0,140.7799988,65,15.25,113.245697021484,31.0677890777588,144.313400268555,...,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308
2,Lesotho,1986,21.14252061,1603960.0,92,109,23.4,66.7168197631836,10.6219997406006,77.3388137817383,...,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308
3,Malawi,1976,39.20110669,5409980.0,179.8,56,4,14.338809967041,15.4878797531128,29.8267002105713,...,-3.28504991531372,-12.8143997192383,-0.0718400031328201,-0.538079977035522,0.749620020389557,-0.12015999853611,-2.48820996284485,-0.187729999423027,0,-4.06232023239136
4,Botswana,1994,5.199306759,1420270.0,55.39999898,117,53,58.7042083740234,16.0785007476807,74.7827072143555,...,-187.5,-19.1625995635986,4.24620914459228,-3.0890998840332,4.7163348197937,-2.58439993858337,-1.81132996082306,1.99651896953583,-0.113150000572205,-6.56795978546143
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,Burkina Faso,1988,48.94457166,8534390.0,107.8,33.5,6.5,35.4728813171387,10.2006902694702,45.6735687255859,...,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308
71,Botswana,1988,7.060807251,1195140.0,56.6,111.75,35.75,135.776702880859,30.8545207977295,166.631195068359,...,160.910507202148,29.0043907165527,-4.24322986602783,-0.316520005464554,13.1129302978516,3.4499249458313,-1.61373996734619,-10.0523996353149,-0.0101199997588992,-1.93843996524811
72,Kenya,1970,33.29286623,11498000.0,102,58,9,9.42126178741455,9.48890781402588,18.9101696014404,...,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308
73,Lesotho,1990,19.96355858,1783000.0,84.6,105,25,67.9856872558594,26.8740100860596,94.8597030639648,...,-0.996479988098144,3.28616809844971,-0.362129986286163,1.02300500869751,0.187684997916222,0.868880987167358,-3.24150991439819,0.836112022399902,0.431519985198975,-0.85632997751236
74,Kenya,1991,28.14106137,24015140.0,61.4,93,28,29.552059173584,21.131010055542,50.6830711364746,...,-4.14308023452759,-4.25638008117676,-18.8342990875244,1.62289297580719,-0.415060013532639,-0.0189299993216991,-0.304329991340637,1.22138798236847,-0.213339999318123,-4.21381998062134

#### Right Inclusive Join
<img src="https://www.dofactory.com/img/sql/sql-right-join.png"/>

In [18]:
df10 = pd.merge(df1,df2, how = 'right')
df10.head(5)

,countryc,year,agrgdp,popn,infmort,schprim,schsec,grtdsbp,grlndsbp,aiddsbp,...,dcurexpp,dcapexpp,dprirepp,dcnlnagp,dcnlnenp,dcnlninp,dcnlntacp,dcnlnedup,dcnlnhthp,dcnlnothp
0,Kenya,1980,32.59223808,16560000.0,72.40000153,115,20,26.8336296081543,17.7571392059326,44.5907592773438,...,-1.90575003623962,4.4354100227356,-0.64258998632431,-0.43707999587059,-2.52485990524292,-0.424710005521774,-3.0382399559021,-0.0560100004076958,0,7.8144268989563
1,Ghana,1973,48.97463727,9388140.0,106,68.2,27.8,7.54381990432739,7.85923004150391,15.4030504226685,...,-13.4622001647949,-5.45116996765137,-0.186719998717308,-0.00694000022485852,-3.54000997543335,0.0770640000700951,-0.0829199999570846,0,0,-0.743390023708344
2,Liberia,1990,1.79769313486232e+308,2435000.0,176.8,1.79769313486232e+308,1.79769313486232e+308,38.6235008239746,16.2881603240967,54.9116592407227,...,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308
3,Madagascar,1981,33.07584521,8951460.0,134,1.79769313486232e+308,1.79769313486232e+308,17.8668098449707,25.6996097564697,43.5664291381836,...,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308
4,Ethiopia,1989,48.50468489,49337260.0,126.8,34,14,15.0112895965576,3.97879600524902,18.9900798797607,...,0.919135987758636,2.5445671081543,0.135925993323326,-0.0909200012683868,-0.922819972038269,0.01554000005126,0.00121000001672655,-0.114739999175072,0.0564300008118153,-3.32821989059448

### Sorting Data

In [19]:
df1.sort_values(by = ['agrgdp'], ascending = True)
df1

,countryc,year,agrgdp,popn,infmort,schprim,schsec,grtdsbp,grlndsbp,aiddsbp,...,dcurexpp,dcapexpp,dprirepp,dcnlnagp,dcnlnenp,dcnlninp,dcnlntacp,dcnlnedup,dcnlnhthp,dcnlnothp
223,Lesotho,1983,23.91304348,1483270.0,98,106.8,21,87.4762725830078,20.0394096374512,107.515701293945,...,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308
150,"Gambia, The",1988,31.22936246,841250.0,140.7799988,65,15.25,113.245697021484,31.0677890777588,144.313400268555,...,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308
226,Lesotho,1986,21.14252061,1603960.0,92,109,23.4,66.7168197631836,10.6219997406006,77.3388137817383,...,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308
296,Malawi,1976,39.20110669,5409980.0,179.8,56,4,14.338809967041,15.4878797531128,29.8267002105713,...,-3.28504991531372,-12.8143997192383,-0.0718400031328201,-0.538079977035522,0.749620020389557,-0.12015999853611,-2.48820996284485,-0.187729999423027,0,-4.06232023239136
52,Botswana,1994,5.199306759,1420270.0,55.39999898,117,53,58.7042083740234,16.0785007476807,74.7827072143555,...,-187.5,-19.1625995635986,4.24620914459228,-3.0890998840332,4.7163348197937,-2.58439993858337,-1.81132996082306,1.99651896953583,-0.113150000572205,-6.56795978546143
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20,Burkina Faso,1988,48.94457166,8534390.0,107.8,33.5,6.5,35.4728813171387,10.2006902694702,45.6735687255859,...,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308
46,Botswana,1988,7.060807251,1195140.0,56.6,111.75,35.75,135.776702880859,30.8545207977295,166.631195068359,...,160.910507202148,29.0043907165527,-4.24322986602783,-0.316520005464554,13.1129302978516,3.4499249458313,-1.61373996734619,-10.0523996353149,-0.0101199997588992,-1.93843996524811
158,Kenya,1970,33.29286623,11498000.0,102,58,9,9.42126178741455,9.48890781402588,18.9101696014404,...,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308,1.79769313486232e+308
230,Lesotho,1990,19.96355858,1783000.0,84.6,105,25,67.9856872558594,26.8740100860596,94.8597030639648,...,-0.996479988098144,3.28616809844971,-0.362129986286163,1.02300500869751,0.187684997916222,0.868880987167358,-3.24150991439819,0.836112022399902,0.431519985198975,-0.85632997751236
179,Kenya,1991,28.14106137,24015140.0,61.4,93,28,29.552059173584,21.131010055542,50.6830711364746,...,-4.14308023452759,-4.25638008117676,-18.8342990875244,1.62289297580719,-0.415060013532639,-0.0189299993216991,-0.304329991340637,1.22138798236847,-0.213339999318123,-4.21381998062134

In [20]:
df1.sort_index(axis = 0, ascending =True)

,countryc,year,agrgdp,popn,infmort,schprim,schsec,grtdsbp,grlndsbp,aiddsbp,...,dcurexpp,dcapexpp,dprirepp,dcnlnagp,dcnlnenp,dcnlninp,dcnlntacp,dcnlnedup,dcnlnhthp,dcnlnothp
5,Burkina Faso,1973,34.83428571,5958700.0,135,14.8,1.6,25.9791507720947,3.87817406654358,29.8573207855225,...,1.79769313486232e+308,1.79769313486232e+308,-4.26292991638184,0.290098994970322,0.0578910000622272,2.53049802780151,-0.38238000869751,0,0,-0.11642000079155
7,Burkina Faso,1975,34.27100776,6202000.0,131,16,2,30.4486293792725,7.36860179901123,37.8172302246094,...,5.94059085845947,0.0831290036439896,0.118987999856472,0.262962996959686,0.517924010753632,-2.78498005867004,0.806988000869751,0.0681129992008209,0,2.65820407867432
8,Burkina Faso,1976,34.80431988,804215.0,129,15,2,24.3181304931641,8.15182018280029,32.4699592590332,...,0.0346110016107559,2.13481593132019,-0.0604999996721744,0.739816009998322,-0.850790023803711,-0.320169985294342,0.252671003341675,0.0882859975099564,0,0.984821021556854
12,Burkina Faso,1980,33.24267254,6962000.0,121,18,3,41.1754417419434,14.5752201080322,55.7506484985352,...,-3.46266007423401,2.54042410850525,-10.8857002258301,0.478792995214462,0.321274012327194,0.0279569998383522,-1.57395005226135,0.079134002327919,0,0.573574006557465
15,Burkina Faso,1983,31.9042673,7490710.0,115.4,24.6,4.2,27.2162609100342,9.1533613204956,36.3696212768555,...,-10.6338996887207,-2.52524995803833,-0.175799995660782,-0.105319999158382,0.0590809993445873,0.223771005868912,2.36123299598694,0.161394998431206,0.00619200011715293,-0.0402799993753433
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
285,Mauritius,1992,10.82725922,1081000.0,18,107,57,32.6669311523438,35.577751159668,68.2446670532226,...,47.5250587463379,31.1174602508545,4.0041389465332,0.32574000954628,-19.9955005645752,0.353338003158569,-3.39756989479065,0,0,4.77696514129639
286,Mauritius,1993,9.715403179,1097000.0,17.35999997,106,59,31.8793106079102,24.5195999145508,56.3989105224609,...,-61.5862998962402,-17.375,8.73153114318848,3.22284603118896,-13.5272998809814,-0.161929994821548,-3.19396996498108,0,0,3.52519607543945
294,Malawi,1974,41.17239788,5087140.0,185.4,51.6,4,8.73302841186524,15.7701101303101,24.5031394958496,...,0.46765199303627,7.48967599868774,-0.0427899993956089,1.00035405158997,0.44098699092865,0,1.25282204151154,0.21764700114727,0,-4.72225999832153
295,Malawi,1975,37.23468769,5244000.0,182.6,53.8,4,10.5895004272461,22.165210723877,32.754711151123,...,0.515770971775055,10.8334703445435,0.043698001652956,-0.280800014734268,0.483336985111237,0.184547007083893,7.19747400283814,-0.14614999294281,0,0.320367008447647
296,Malawi,1976,39.20110669,5409980.0,179.8,56,4,14.338809967041,15.4878797531128,29.8267002105713,...,-3.28504991531372,-12.8143997192383,-0.0718400031328201,-0.538079977035522,0.749620020389557,-0.12015999853611,-2.48820996284485,-0.187729999423027,0,-4.06232023239136

### Selecting and Slicing Data

In [21]:
df1[['countryc', 'year']]

         countryc  year
223       Lesotho  1983
150   Gambia, The  1988
226       Lesotho  1986
296        Malawi  1976
52       Botswana  1994
..            ...   ...
20   Burkina Faso  1988
46       Botswana  1988
158         Kenya  1970
230       Lesotho  1990
179         Kenya  1991

[75 rows x 2 columns]

In [22]:
df1.iloc[:,1:8].head()

,year,agrgdp,popn,infmort,schprim,schsec,grtdsbp
223,1983,23.91304348,1483270.0,98,106.8,21,87.4762725830078
150,1988,31.22936246,841250.0,140.7799988,65,15.25,113.245697021484
226,1986,21.14252061,1603960.0,92,109,23.4,66.7168197631836
296,1976,39.20110669,5409980.0,179.8,56,4,14.338809967041
52,1994,5.199306759,1420270.0,55.39999898,117,53,58.7042083740234

### Grouping & Aggregating

In [23]:
df1.groupby(['year', 'infmort']).agg(np.mean)

                        popn
year infmort
1970 102          11498000.0
     110.5999985   8614000.0
     177.8000031   1385000.0
     59.79999924    829000.0
1971 122.4000015   6664330.0
...                      ...
1994 100.600001   10085790.0
     55.39999898   1420270.0
     59           26017040.0
     77.39999898   1938930.0
1995 89.04000092  13651000.0

[75 rows x 1 columns]

In [24]:
df1.groupby(['schsec']).groups

{'1.6': Int64Index([5], dtype='int64'),
 '1.79769313486232e+308': Int64Index([246, 205, 234, 250], dtype='int64'),
 '10': Int64Index([89, 184, 137], dtype='int64'),
 '11.8': Int64Index([214], dtype='int64'),
 '12': Int64Index([101, 241, 238, 239], dtype='int64'),
 '13': Int64Index([215, 144, 59], dtype='int64'),
 '14': Int64Index([216, 106], dtype='int64'),
 '15.25': Int64Index([150], dtype='int64'),
 '16': Int64Index([152], dtype='int64'),
 '17.66666667': Int64Index([190], dtype='int64'),
 '18': Int64Index([261, 166, 34, 63, 64], dtype='int64'),
 '19': Int64Index([221], dtype='int64'),
 '2': Int64Index([8, 7], dtype='int64'),
 '20': Int64Index([66], dtype='int64'),
 '21': Int64Index([223, 173], dtype='int64'),
 '22': Int64Index([224, 201], dtype='int64'),
 '22.16666667': Int64Index([176, 175], dtype='int64'),
 '23': Int64Index([225], dtype='int64'),
 '23.2': Int64Index([108], dtype='int64'),
 '23.4': Int64Index([226], dtype='int64'),
 '23.8': Int64Index([227], dtype='int64'),
 '24': Int64Index([254], dtype='int64'),
 '25': Int64Index([182, 230], dtype='int64'),
 '26': Int64Index([253, 73], dtype='int64'),
 '28': Int64Index([74, 179], dtype='int64'),
 '3': Int64Index([12], dtype='int64'),
 '30': Int64Index([263], dtype='int64'),
 '33.5': Int64Index([45], dtype='int64'),
 '35.75': Int64Index([46], dtype='int64'),
 '37': Int64Index([111], dtype='int64'),
 '38': Int64Index([129], dtype='int64'),
 '39.75': Int64Index([122], dtype='int64'),
 '4': Int64Index([296, 294, 295], dtype='int64'),
 '4.2': Int64Index([15], dtype='int64'),
 '4.4': Int64Index([81], dtype='int64'),
 '40.6': Int64Index([118], dtype='int64'),
 '48': Int64Index([271], dtype='int64'),
 '51.6': Int64Index([282], dtype='int64'),
 '53': Int64Index([52], dtype='int64'),
 '57': Int64Index([285], dtype='int64'),
 '59': Int64Index([286], dtype='int64'),
 '6.5': Int64Index([20], dtype='int64'),
 '7.6': Int64Index([133], dtype='int64'),
 '8': Int64Index([22, 90], dtype='int64'),
 '8.2': Int64Index([55], dtype='int64'),
 '9': Int64Index([26, 158], dtype='int64'),
 '9.4': Int64Index([212, 136], dtype='int64'),
 '9.6': Int64Index([92], dtype='int64')}